version: "3.8"

#NETWORK
networks:
  my-network:
    driver: bridge
#SERVICES
services: 
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.29
    hostname: mysqldb
    restart: always
    environment:
      - MYSQL_DATABASE=hdshopdb
      - MYSQL_ROOT_PASSWORD=123456
    networks: 
      - my-network
    ports:
      - 3307:3306
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=123456 --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 10s
      retries: 100

  api_service:
    depends_on:
      mysqldb:
        condition: service_healthy
    container_name: beshop
    networks: 
      - my-network
    build: 
      dockerfile: Dockerfile
      context: ./beshop/
    hostname: beshop-springboot
    restart: always
    ports:
      - 9090:8080
    environment:
      - MYSQL_HOST=mysqldb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_PORT=3306


